apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpRENDQVMrZ0F3SUJBZ0lRREpvUDNLSmVYakhUVCtMQmpGZVJ0VEFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNRGd4TXpFeE16TXpPVm9YRFRNMU1EZ3hNVEV4TXpNegpPVm93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCTW9ZbmNvckRtcjMvNkdqdHEzcDVwZGFPZjJEdHBPc1dHQUszdkNNSW5OK3hFcEk1SWEzVHdDQ2E3ZVMKeEg5Z28yNkJGQm83aFFORWZScURUMGdFaTZpallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVPeTNlM2ptSS9nTW9NV0ZKRTYrN3dMS0RZcUF3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnU0x2TmExYWsKc3VMaGdiaTR2bS9tczVzc1BDdG13T0NJblZQSmNROFpDUThDSUNaOFpMdVBwalgvYktOLzZFU1lReUJPMUVGMgpCWDNwVURiUXNRNWo2cHIvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://10.0.0.250:6443
  name: talos-cluster
contexts:
- context:
    cluster: talos-cluster
    namespace: default
    user: admin@talos-cluster
  name: admin@talos-cluster
current-context: admin@talos-cluster
kind: Config
preferences: {}
users:
- name: admin@talos-cluster
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoRENDQVNxZ0F3SUJBZ0lRTUp3R2VMdFFXNnNnZ1UxdkRjaVRlREFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNRGd4TmpBMk16Z3hNVm9YRFRJMk1EZ3hOakEyTXpneQpNVm93S1RFWE1CVUdBMVVFQ2hNT2MzbHpkR1Z0T20xaGMzUmxjbk14RGpBTUJnTlZCQU1UQldGa2JXbHVNRmt3CkV3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFSW1RSTJlWlZTeDU5MUUvQ2kvSlFZUDAyckJvVkxkcDcKSW5iU2k3Vm50Uy9CamI3WVVkRFJSQnJ4K3RyVDkwZ05JNHZzbG5FZEFic3Jrc3JQOXFpaGNhTklNRVl3RGdZRApWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01COEdBMVVkSXdRWU1CYUFGRHN0CjN0NDVpUDRES0RGaFNST3Z1OEN5ZzJLZ01Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lER2JHK1l0cXB4SndBY3YKSXY5eDBvVFBHWHdlNHA0dVpIN1Q3bnFyc2V4b0FpRUFnTVMwcGVKQlZNV3hqU1c3djVFdnlab3YrNVU4Vyttego1MFNIaFBuN0RKaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1XRGp2cjM5TXEyK1NScnpmbHVvdnJwWTU5eFY5aHYvNk9OMVNKdnZ5TWVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFSW1RSTJlWlZTeDU5MUUvQ2kvSlFZUDAyckJvVkxkcDdJbmJTaTdWbnRTL0JqYjdZVWREUgpSQnJ4K3RyVDkwZ05JNHZzbG5FZEFic3Jrc3JQOXFpaGNRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
